<a href="https://colab.research.google.com/github/jeniferGoncalvesDaSilvaDev/numpy-learning/blob/main/numpy_aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
#um array, pode ser classificado
#1D- 1 dimensão, um vector ou vetor
#2D- 2 dimensões, matriz
#3d- 3 dimensões, tensor

In [2]:
#criando um array
array = np.array([[24,5,6,8], [235,56,98,40]])
#uma matriz, array de 2D
print(array)

[[ 24   5   6   8]
 [235  56  98  40]]


In [3]:
print(type(array))

<class 'numpy.ndarray'>


In [4]:
#um array, que tem a diagonal principal ou secundária com zeros ou uns
zero_array = np.zeros(shape=(5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [5]:
#array com valores de 1
um_array = np.ones(shape =(2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#craindo um array vazio
#cria valores aleatorios
vazio_array = np.empty(shape =(3,4))
print(vazio_array)

[[6.62075822e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [8]:
#criar um array com um intervalo de números
array_intervalo = np.arange(10)
print(array_intervalo)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#comecar com um valor:50, vai de 30 em 30, até 200
array_intervalo2=np.arange(50,200,30)
print(array_intervalo2)

[ 50  80 110 140 170]


In [13]:
#array com sequência
#o argumento num, eh o tamanho do array
#retstep, considera intervalos da equação da reta, o valor da inclinação
#endpoint, considera o intervalo dado, ex: de 0 a 100, seu padrão eh True
array_linear = np.linspace(0,100,num=20,endpoint=True,retstep=True)
print(array_linear)

(array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ]), 5.2631578947368425)


In [14]:
#descobrindo o tamanho do array
zero_array = np.zeros(shape=(5,3,6))
print(zero_array)
#forma do array, seus valores em cada eixo
print(zero_array.shape)
#quantos dados, eixo x vezes eixo y, vezes eixo z
print(zero_array.size)
#numero de dimensoes
print(zero_array.ndim)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(5, 3, 6)
90
3


In [15]:
array2= np.array([1,2,3])
print(array2)
print(array.shape)
print(array.ndim)

[1 2 3]
(2, 4)
2


In [16]:
array2d = array2[np.newaxis,:]
print(array2d.shape)
print(array2d.ndim)
print(array2d)

(1, 3)
2
[[1 2 3]]


In [17]:
array2d3 = array2[:,np.newaxis]
print(array2d3.shape)
print(array2d3.ndim)
print(array2d3)

(3, 1)
2
[[1]
 [2]
 [3]]


In [18]:
#acessando item de um array
print(array2d3[2][0])

3


In [19]:
#concatenando arrays
a = np.array([41,2,3])
b = np.array([22,98,74])
#concatenate, passa uma tupla por parametro
c = np.concatenate((a,b))
d = np.concatenate((b,a))
print(c)
print(d)

[41  2  3 22 98 74]
[22 98 74 41  2  3]


In [32]:
#consultando itens de um array
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print('------------')
maior_8= a [a>8]
print(maior_8)

print('-------------')
#numeros pares
resto = a[a%2==0]
print(resto)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------
[ 9 10 11 12]
-------------
[ 2  4  6  8 10 12]


In [33]:
#operaçoes com arrays
a = np.array([1,2,3])
soma = a.sum()
max = a.max()
min = a.min()
media = a.mean()
print(soma)
print(max)
print(min)
print(media)

6
3
1
2.0


In [39]:
#gerar numeros aleatorios
from numpy.random import default_rng
rng = default_rng()
#gerar numeros aleatorio inteiro
#o primeiro argumento ate onde vai o array, o segundo, as dimensoes do array
integers = rng.integers(20, size=(2,4))
print(integers)

[[10  4  2  1]
 [ 8  6  5 17]]


In [48]:
#arrays não permitem tipos de dados distintos:
#array quando rece dados dinstintos, coneverte em str
array = np.array([1,2,'Jenifer',3,4,5,6,7])
print(array)

['1' '2' 'Jenifer' '3' '4' '5' '6' '7']


In [47]:
#já as listas sim:
lista = [1,2 ,'Jenifer',3,4]
print(lista)

[1, 2, 'Jenifer', 3, 4]
