<a href="https://colab.research.google.com/github/jeniferGoncalvesDaSilvaDev/numpy-learning/blob/main/numpy_aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#um array, pode ser classificado
#1D- 1 dimensão, um vector ou vetor
#2D- 2 dimensões, matriz
#3d- 3 dimensões, tensor

In [ ]:
#criando um array
array = np.array([[24,5,6,8], [235,56,98,40]])
#uma matriz, array de 2D
print(array)

[[ 24   5   6   8]
 [235  56  98  40]]


In [ ]:
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
#um array, que tem a diagonal principal ou secundária com zeros ou uns
zero_array = np.zeros(shape=(5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
#array com valores de 1
um_array = np.ones(shape =(2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#craindo um array vazio
#cria valores aleatorios
vazio_array = np.empty(shape =(3,4))
print(vazio_array)

[[4.7121343e-310 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
#criar um array com um intervalo de números
array_intervalo = np.arange(10)
print(array_intervalo)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#comecar com um valor:50, vai de 30 em 30, até 200
array_intervalo2=np.arange(50,200,30)
print(array_intervalo2)

[ 50  80 110 140 170]


In [ ]:
#array com sequência
#o argumento num, eh o tamanho do array
#retstep, considera intervalos da equação da reta, o valor da inclinação
#endpoint, considera o intervalo dado, ex: de 0 a 100, seu padrão eh True
array_linear = np.linspace(0,100,num=20,endpoint=True,retstep=False)
print(array_linear)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [ ]:
#descobrindo o tamanho do array
zero_array = np.zeros(shape=(5,3,6))
print(zero_array)
#forma do array, seus valores em cada eixo
print(zero_array.shape)
#quantos dados, eixo x vezes eixo y, vezes eixo z
print(zero_array.size)
#numero de dimensoes
print(zero_array.ndim)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(5, 3, 6)
90
3


In [ ]:
array2= np.array([1,2,3])
print(array2)
print(array.shape)
print(array.ndim)

[1 2 3]
(2, 4)
2


In [ ]:
array2d = array2[np.newaxis,:]
print(array2d.shape)
print(array2d.ndim)
print(array2d)

(1, 3)
2
[[1 2 3]]


In [ ]:
array2d3 = array2[:,np.newaxis]
print(array2d3.shape)
print(array2d3.ndim)
print(array2d3)

(3, 1)
2
[[1]
 [2]
 [3]]


In [ ]:
#acessando item de um array
print(array2d3[2][0])

3


In [ ]:
#concatenando arrays